name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          node-version: 16.x
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
        env:
          REACT_APP_WAITLIST_CODE: ${{ secrets.REACT_APP_WAITLIST_CODE }}
          REACT_APP_EMAILJS_SERVICE_CODE: ${{ secrets.REACT_APP_EMAILJS_SERVICE_CODE }}
          REACT_APP_EMAILJS_TEMPLATE_CODE: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_CODE }}
          REACT_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: build
